image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  NAME: imtlab/baseimage-golang
  VERSION: "18.0.1"

services:
  - docker:18.09.7-dind

stages:
  - build
  - test
  - push

before_script:
  - apk add --update alpine-sdk bash

build-1.13:
  stage: build
  artifacts:
   paths:
    - build-1_13.tgz
   expire_in: 1 day
  script:
    - make build_golang113
    - docker save $NAME:1.13-$VERSION | gzip > build-1_13.tgz


test-all:
  stage: test
  script:
    - gunzip -c build-1_13.tgz   | docker load
    - make test
  dependencies:
    - build-1.13

push-all:
  stage: push
  only:
    - tags
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - gunzip -c build-1_13.tgz   | docker load
    - make release
  dependencies:
    - build-1.13
